name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: wasilibs/actions/.github/workflows/ci.yaml@c6c4d5418f5f5ad5a25bba3ca44875c4ed1e9564
    secrets: inherit
