name: "Release"

on:
  push:
    tags:
      - v*

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  release:
    uses: wasilibs/actions/.github/workflows/release.yaml@1d6b721459abbe97e848c42120c827117fbfb2c5
    secrets: inherit
