name: "Update Upstream"

on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    uses: wasilibs/actions/.github/workflows/update-node.yaml@1d6b721459abbe97e848c42120c827117fbfb2c5
    with:
      packages: "@bufbuild/protoc-gen-es"
    secrets: inherit
